import { chromium } from 'playwright';
const B = 'http://localhost:5180';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message));
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('TUNNEL')) errors.push('CONSOLE ' + m.text()); });
const shot = (n, full) => page.screenshot({ path: `/tmp/shots/${n}.png`, fullPage: !!full });
// imagen de prueba
await page.setContent('<div style="width:600px;height:380px;background:linear-gradient(45deg,#1e3a8a,#34d399);color:white;font:40px Arial;padding:30px">DRIVER LICENSE<br>JUAN PEREZ</div>');
await page.locator('div').screenshot({ path: '/tmp/lic.png' });
await page.goto(B + '/registro');
await page.waitForTimeout(500);
await shot('20-registro');
const f = (label, v) => page.locator(`label:has-text("${label}") input`).first().fill(v);
await f('Nombre', 'Maria'); await f('Apellido', 'Lopez'); await f('Teléfono', '3025551111');
await f('Usuario', 'maria.lopez'); await f('Contraseña', 'secreto123'); await f('Repite', 'secreto123');
await page.click('button[type=submit]');
await page.waitForURL('**/portal');
await page.waitForTimeout(600);
await shot('21-portal', true);
// intentar enviar sin datos
await page.click('text=Enviar mi información');
await page.waitForTimeout(300);
console.log('toast:', await page.locator('.fixed.bottom-4').innerText());
await f('Fecha de nacimiento', '1990-05-04');
await f('Seguro Social', '987654321');
await f('Calle y número', '77 Elm St'); await f('Ciudad', 'Bear');
await page.locator('label:has-text("Estado") select').selectOption('DE');
await f('ZIP', '19701');
const inputs = page.locator('input[type=file][capture]');
await inputs.nth(0).setInputFiles('/tmp/lic.png');
await page.waitForSelector('text=Documento guardado');
await inputs.nth(2).setInputFiles('/tmp/lic.png');
await page.waitForTimeout(1200);
await shot('22-portal-docs', true);
await page.click('text=Enviar mi información');
await page.waitForTimeout(800);
await shot('23-portal-done', true);
// admin ve el registro
await page.click('text=Salir');
await page.waitForURL('**/login');
await page.setViewportSize({ width: 1400, height: 900 });
await f('Usuario o email', 'admin@test.com'); await page.fill('input[type=password]', 'password123');
await page.click('button[type=submit]');
await page.waitForURL('**/admin');
await page.waitForTimeout(600);
await page.click('a:has-text("Clientes")');
await page.waitForTimeout(500);
await shot('24-clientes');
await page.click('text=Maria Lopez');
await page.waitForTimeout(500);
await page.click('button:has-text("Documentos")');
await page.waitForTimeout(800);
await shot('25-docs-admin');
// agregar item manual a Maria (3 bureaus) y editar
await page.click('button:has-text("Cuentas")');
await page.waitForTimeout(300);
await page.click('button:has-text("Agregar")');
await page.locator('label:has-text("Acreedor / Compañía") input').fill('LVNV FUNDING');
await page.locator('label:has-text("Balance") input').fill('455');
await page.click('button:has-text("Guardar") >> nth=-1');
await page.waitForTimeout(600);
console.log('manual rows:', await page.locator('td:has-text("$455.00")').count());
await page.locator('button[aria-label=Editar]').first().click();
await page.waitForTimeout(300);
await page.locator('label:has-text("Estado") select').first().selectOption('eliminada');
await page.waitForTimeout(200);
await shot('26-edit-item');
await page.click('button:has-text("Guardar") >> nth=-1');
await page.waitForTimeout(600);
await page.click('button:has-text("Cobros")');
await page.waitForTimeout(400);
console.log('charge created:', await page.locator('td:has-text("$150.00")').count());
await page.goto(B + '/admin/clientes');
await page.waitForTimeout(500);
await page.locator('tr:has-text("Maria Lopez") button[aria-label=Borrar]').click();
await page.click('text=Borrar >> nth=-1');
await page.waitForTimeout(700);
console.log('maria deleted:', (await page.locator('text=Maria Lopez').count()) === 0);
console.log('ERRORS', JSON.stringify(errors, null, 1));
await browser.close();
